m-danya/improve coordinate system
m-danya/the-hammer-lord pull request #10
Opened 2022-11-16 21:22 UTC by m-danya

This branch redefines the coordinate system and improve camera movement with axes-locking feature. Fixed issues: #5, #8. New issue arised: #9.

2022-11-18 23:05 UTC, Alucardik requested changes
Камера стала куда плавнее, и вроде коллизии действительно заработали - приятно) Правда, у меня на маке vsync не завелся, но мб дело в ос

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/main.py
> +    # public property that is utilized by Player and Camera classes
Не называл бы это `public property`, так как возникает путаница с понятиями из ООП, а тут никакого класса нет

Мб просто `player input getter` обозвать это? На скоупы в целом пофиг, тк ты и так пишешь, что он используется камерой и игроком

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +        # TODO: move collision logic to Entity OR to CollidablesStorage
Тудушка замечена, главное про нее не забыть)

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +                raise NotImplementedError
мб переписать через match case? Семантически лучше ложится

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +    def is_on_land(self):
Я бы вместо land использовал ground какой-нибудь, потому что on land чаще используется при сопоставлении с in the sea / ocean

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/settings.py
> +MAGIC_COLLISION_SHIFT = 1
В будущем точно стоит выпилить подобную константу) магии быть не должно

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +                self._vx = 0
Я бы проверку коллизий такую вынес в отдельную функцию, которая принимала бы список спрайтов и ось для проверки, а возвращала бы bool

Чтобы код не дублировать

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/collidables_storage.py
> +    objects: list[CollisionSurface] = []
А почему тут лист именно CollisionSurface? У нас же тут могут и отдельные спрайты добавляться, типа платформ на уровне

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/ui/debug_info_corner.py
> +        if self.enabled:
Мб чтобы вложенность if-ом не повышать, сделать if !enabled -> return?

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +    def detect_locked_axes(self, lvl_size):
Добавить бы тайп-хинт)

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/ui/debug_info_corner.py
> +            font = pygame.font.Font(None, 42)
А зачем на каждый рендер создавать статический объект? Я бы его вынес в поля класса

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/ui/debug_info_corner.py
> +            }
Я бы вынес сбор этой кроказябры в отдельную функцию, чтобы в update было что-то вроде `debug_data = self._collect_debug_data()`

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                target_x = self._player.rect.centerx - self.viewport_size[0] // 2
Не стоит вызывать лишний раз геттер, лучше обратиться напрямую к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                target_y = self._player.rect.centery - self.viewport_size[1] // 2
Лучше обратиться к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                self._player.rect.centerx - self.viewport_size[0] // 2 > 0
Лучше обратиться к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                and self._player.rect.centerx + self.viewport_size[0] < lvl_size[0]
Лучше бы обратиться к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                self._player.rect.centery - self.viewport_size[1] // 2 > 0
Лучше бы обратиться к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +                and self._player.rect.centery + self.viewport_size[1] // 2 < lvl_size[1]
Лучше бы обратиться к приватному полю

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +        for collidables in collidablesStorage.objects:
У тебя поле objects объявлено как [CollisionSurface], а тут ты определяешь разные типы объектов

Надо как-нибудь переделать тайп-хинт

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +            self, collidablesStorage.objects[0].get_sprites(), False
Почему ты именно к 0 элементу тут обращаешься? Считается, что это пол? Если да, то какое-то неявное предположение, плюс кажется дублируется вызов get_sprites с циклом выше

Надо бы как-нибудь это логику вынести, чтобы ясно было, что берется пол (а вообще потом будет и пол, и потолок, и платформы всякие)

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +import pygame.key
Мб этот экспорт к экспорту ниже добавить?

2022-11-18 23:05 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +    def move_to_target(target_x: int, current_x: int):
Вроде ты этот метод используешь для приближения и по x, и по y, поэтому я бы заренеймил параметры

2022-11-19 17:13 UTC, m-danya commented on the_hammer_lord/main.py
> +    # public property that is utilized by Player and Camera classes
ой да, я чета подумал, что мы в объекте

2022-11-19 17:14 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +        # TODO: move collision logic to Entity OR to CollidablesStorage
ну как только начнём врагов писать, сразу очевидное дублирование будет иначе, я думаю, что не пропустим)

2022-11-19 17:16 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +                raise NotImplementedError
оч круто. не знал, что так можно

2022-11-19 17:19 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +                raise NotImplementedError
Done

2022-11-19 17:20 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def is_on_land(self):
Done

2022-11-19 17:21 UTC, m-danya commented on the_hammer_lord/settings.py
> +MAGIC_COLLISION_SHIFT = 1
Ща гс запишу насчёт этой штуки, тут от магии не избавиться)

2022-11-19 17:26 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +                self._vx = 0
Мне кжц придётся оставить так, как есть, потому что
- для разных осей надо брать разные аттрибуты у ректов: left/top и right/bottom
- для y надо ставить `self._is_on_the_ground=True`, если чел упал 
- оси всего две, не страшно

2022-11-19 17:27 UTC, m-danya commented on the_hammer_lord/utils/collidables_storage.py
> +    objects: list[CollisionSurface] = []
пока сотру тогда тайпинг, всё равно этот класс переписывать к чертям

2022-11-19 17:27 UTC, m-danya commented on the_hammer_lord/ui/debug_info_corner.py
> +        if self.enabled:
Done

2022-11-19 17:28 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +    def detect_locked_axes(self, lvl_size):
Done

2022-11-19 17:30 UTC, m-danya commented on the_hammer_lord/ui/debug_info_corner.py
> +            font = pygame.font.Font(None, 42)
Done

2022-11-19 17:35 UTC, m-danya commented on the_hammer_lord/main.py
> +    # public property that is utilized by Player and Camera classes
Done

2022-11-19 17:36 UTC, m-danya commented on the_hammer_lord/ui/debug_info_corner.py
> +            }
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +                target_y = self._player.rect.centery - self.viewport_size[1] // 2
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +                self._player.rect.centerx - self.viewport_size[0] // 2 > 0
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +                and self._player.rect.centerx + self.viewport_size[0] < lvl_size[0]
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +                self._player.rect.centery - self.viewport_size[1] // 2 > 0
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +                and self._player.rect.centery + self.viewport_size[1] // 2 < lvl_size[1]
Done

2022-11-19 17:40 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +        for collidables in collidablesStorage.objects:
Done выше, заменил на `any` в надежде на скорый рефакторинг с переписыванием этого недокласса

2022-11-19 18:21 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +            self, collidablesStorage.objects[0].get_sprites(), False
да, тут должно было быть `sprites`, вот что дублирование кода творит!!

2022-11-19 18:22 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +            self, collidablesStorage.objects[0].get_sprites(), False
Done

2022-11-19 18:23 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +import pygame.key
забавно, но тут `.key` лишнее
Done

2022-11-19 18:27 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +    def move_to_target(target_x: int, current_x: int):
да, просто я не придумал как назвать красиво

2022-11-19 18:29 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +    def move_to_target(target_x: int, current_x: int):
переименовал, Done

2022-11-21 08:37 UTC, Alucardik approved these changes

2022-11-21 08:37 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +                self._vx = 0
Хм, ну окей, мб потом поправим, когда будем переносить в collidableStorage код

2022-11-21 08:51 UTC, merged