(Alucardik) add keyboard input
m-danya/the-hammer-lord pull request #4
Opened 2022-10-28 12:12 UTC by Alucardik

Solves issue #1

2022-10-28 17:20 UTC, m-danya requested changes
Красота! Понаоставлял комментов, там в основном вопросы скорее, чем правки)

1. Враги щас почему-то вместе с игроком прыгают, это как так ахахах
2. Почему сначала идешь по прямой вправо-влево, а если прыгнуть, то сваливаешься вниз? Это типа платформа какая-то? Просто обычно спрыгивание сделано по-другому, тут оч странно, (особенно без текстур). 

Upd. Пока код смотрел, ваще не понял, откуда там такой эффект взялся с начальной "платформой" в воздухе 🤔

2022-10-28 17:20 UTC, m-danya commented on README.md
> +python3.10 -m venv venv    # optional, python3.9-venv is required
`python3.9-venv is required`
))

2022-10-28 17:20 UTC, m-danya commented on README.md
> +python3.10 -m venv venv    # optional, python3.9-venv is required
мб кстати заменить python3.10 на python3, потому что в убунте 22.04, например, это как раз 3.10

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/controls/controls.py
> +        self._motion_vector = [0, 0]
_jumping задаётся выше, а _motion_vector тут, можно унифицировать для красоты

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/controls/controls.py
> +        return self._motion_vector[1] != 0
типа если падает, то там отрицательное значение, и он тоже в воздухе, да?

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/controls/controls.py
> +            self._motion_vector[1] += GRAVITY_FORCE
пока эту строчку не увидел, казалось, что ты прям честно написал с ускорением))

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +                    case pygame.JOYAXISMOTION:
если мы сделаем, что игрок может выбрать клаву при подключенном джойстике, то такой ивент может прилететь, если игрок дернет геймпад, и функция получит неожиданные аргументы

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +                    case pygame.JOYAXISMOTION:
мб сделать все параметры у обеих реализаций с keyword-аргументами? и типа по дефолту там 0 будет, что там, что там

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +            # as camera follows our player, we're moving it first
лол я как раз про эти строчки говорил, что когда я их менял местами, начиналось дёрганье игрока)) поменяй их назад и заметишь, что тогда в конце игрок не дергается, не становится как будто на место)

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/entities/enemy.py
> +from .object import GameObject
давай везде придерживаться абсолютных импортов) и в других местах тогда тоже, не буду писать везде одно и то же

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/entities/object.py
> +class GameObject:
может переименовать в BaseEntity?
Я первые несколько минут думал, что это объект, который характеризует какое-то состояние игры, и что он должен куда-то прокидываться

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def camera_adjusted_coords(self) -> Vector2D:
~~а если камера будет двигаться относительно игрока? или у нас не будет~~

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def camera_adjusted_coords(self) -> Vector2D:
~~не понял просто зачем такой метод нужен, если раньше через объект `camera` вроде более логично получались координаты, не?~~

увидел, что камера привязывается к игроку наоборот, да, так прикольнее.

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +            motion_vector[1] = 0
так вроде моушн вектор нигде дальше не используется, не?
если условие не выполнено, то он не изменит координаты, зачем еще вектор занулять?

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +    # TODO: encapsulate in Player class
типа запихнуть выбор способа управления внутрь Player-а? вроде норм идея

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +        logging.error("No controller detected, falling back to keyboard insert")
instead?

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +    camera.bind_player(player)
справедливо

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +    # as we're moving towards a 2d platformer enemies are not collidable anymore
хм звучит хайпово в принципе)

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +    # as we're moving towards a 2d platformer enemies are not collidable anymore
но будешь получать урон от столкновения, как в марио

ну или нет)

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/main.py
> +                    case pygame.JOYAXISMOTION:
не уверен, что это лучше, но как-то надо решить то, что я выше описал, наверное

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/settings.py
> +PLAYER_COORDS_CENTERED = (SCREEN_SIZE[0] // 2 + PLAYER_SHIFT_FROM_CENTER_X,
давай пользоваться black, чтобы форматирование совпадало? вроде он скобки поставит на отдельных строках

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/settings.py
> -camera = Camera(0, 0)
оо круто что эти костыли пропали с импортами в нужном порядке))

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +from __future__ import annotations
почему из будущего? неужели фишки питонов >= 3.11?
а, это мб перенесённый мой код, если так, то это можно стереть мб

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +if tp.TYPE_CHECKING:
нифига себе, прикольно

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +    player: tp.Optional[Player] = None
мб всё-таки `import typing`, без сокращения? а конкретно тут мб `from typing import Optional`? мне кжц так красивее, но это имхо

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +        # if player is bound, camera follows it
прикольно

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/camera.py
> +        self.x += motion_vector[0] * CAMERA_SPEED
да, прикольно, потом отдельно этот вектор скорости как-то будем передавать просто

2022-10-28 17:20 UTC, m-danya commented on the_hammer_lord/utils/collidables_storage.py
> +    # TODO: add collision direction check (see MovementDir enum)
а можно поподробнее, зачем учитывать направление?

2022-10-28 19:57 UTC, Alucardik commented
> Враги щас почему-то вместе с игроком прыгают, это как так ахахах

Я просто не трогал твою логику следования врагов, поэтому они буквально за ним повторяют) Офк это надо менять, но pr не про это, думаю, что надо отдельно менять уже

> Почему сначала идешь по прямой вправо-влево, а если прыгнуть, то сваливаешься вниз? Это типа платформа какая-то? 
Просто обычно спрыгивание сделано по-другому, тут оч странно, (особенно без текстур).

Просто я пока захардкодил константу уровня пола (1500 вроде, в player.py можно глянуть), а игрок у тебя по умолчанию спавнится на большой высоте, при этом, игра по умолчанию считает, что игрок стоит на полу; опять же не хотел что-то делать с этим в этом pr-е, потому что нужно уже реализовывать нормально пол и потолок и трекать коллизии с ними

2022-10-28 19:58 UTC, Alucardik commented on the_hammer_lord/utils/collidables_storage.py
> +    # TODO: add collision direction check (see MovementDir enum)
Ну нам нужно трекать, например, границы уровня, которые не позволяют игроку двинуться влево или вправо, но позволяют прыгать

Еще нужно понимать, мы столкнулись с объектом при прыжке или приземлении, тут нужно уже по вертикали трекать коллизии

2022-10-28 20:00 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +    player: tp.Optional[Player] = None
Ну хз, мне, во-первых, очень не нравится печатать целиком typing) во-вторых, на проде всегда видел именно сокращение tp (иногда еще t встречал, но реже)

2022-10-28 20:01 UTC, Alucardik commented on the_hammer_lord/controls/controls.py
> +        return self._motion_vector[1] != 0
Да, только если падает, то положительно, наоборот, в pygame это инвертировано

2022-10-28 20:02 UTC, Alucardik commented on the_hammer_lord/controls/controls.py
> +        self._motion_vector = [0, 0]
Соглы, вынесу

2022-10-28 20:03 UTC, Alucardik commented on README.md
> +python3.10 -m venv venv    # optional, python3.9-venv is required
Можно поправить, оки

2022-10-28 20:04 UTC, Alucardik commented on the_hammer_lord/main.py
> +                    case pygame.JOYAXISMOTION:
Да, согласен, проблема есть, думал тож над ее решением, но предлагаю завести отдельный pr для ее решения, чтобы не стоппится сейчас, тк очень нужна новая реализация карты и коллизий

2022-10-28 20:52 UTC, m-danya commented
Очень забавно про повторение за игроком и про платформу)

2022-10-28 20:56 UTC, m-danya commented on the_hammer_lord/utils/collidables_storage.py
> +    # TODO: add collision direction check (see MovementDir enum)
Ну щас с прыжком будет все нормально же, если двигаться вверх, то он разрешит, и все будет ок

2022-10-31 13:52 UTC, Alucardik commented on the_hammer_lord/main.py
> +            # as camera follows our player, we're moving it first
Не вижу, честно говоря, особо разницы, но тк теперь камера наследует координаты игрока, то она будет на один кадр запаздывать за игроком, если вернуть их, как было

2022-10-31 13:56 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +            motion_vector[1] = 0
Это был какой-то костыль на время тестирования прыжков, уберу действительно

2022-10-31 13:58 UTC, Alucardik commented on the_hammer_lord/main.py
> +        logging.error("No controller detected, falling back to keyboard insert")
Типа добавить в конце предложения хочешь? Вообще fall back и так предполагает переход к другому методу

instead, конечно, можно вставить, но смысловая нагрузка предложения никак не изменится

2022-10-31 14:02 UTC, Alucardik commented on the_hammer_lord/utils/camera.py
> +from __future__ import annotations
Это нужно для работы, чтобы не прятать за кавычками референс типа, а использовать его напрямую (тут это `Player`): https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING (см. Note)

2022-10-31 14:03 UTC, Alucardik commented on the_hammer_lord/main.py
> +    # TODO: encapsulate in Player class
Да, что-то вроде такого, потом это можно будет привязать к ui настроек

Но это опять же в другом pr)

2022-10-31 14:07 UTC, Alucardik commented on the_hammer_lord/settings.py
> +PLAYER_COORDS_CENTERED = (SCREEN_SIZE[0] // 2 + PLAYER_SHIFT_FROM_CENTER_X,
Да, общий стиль это правда хорошо... Мне не оч нравится, как он форматирует, но ладно, давай так

2022-10-31 14:09 UTC, Alucardik commented on the_hammer_lord/utils/collidables_storage.py
> +    # TODO: add collision direction check (see MovementDir enum)
Ну сверху будет потолок, который должен ограничивать прыжок

2022-10-31 14:18 UTC, m-danya commented on the_hammer_lord/main.py
> +            # as camera follows our player, we're moving it first
Я проверял на твоём патчсете и вроде было лучше, если поменять эти две строчки местами назад🤔

2022-10-31 14:20 UTC, Alucardik commented on the_hammer_lord/main.py
> +            # as camera follows our player, we're moving it first
Ну тогда предлагаю завести ишью насчет этого, и в будущем посмотреть на поведение тож

2022-10-31 14:21 UTC, m-danya commented on the_hammer_lord/main.py
> +        logging.error("No controller detected, falling back to keyboard insert")
А, не, я подумал, что ты опечатался (insert <-> instead), не встречал просто такого словосочетания)

2022-10-31 14:22 UTC, m-danya commented on the_hammer_lord/utils/collidables_storage.py
> +    # TODO: add collision direction check (see MovementDir enum)
Точно

2022-10-31 14:25 UTC, m-danya approved these changes

2022-10-31 14:31 UTC, merged