Alucardik/level abstraction
m-danya/the-hammer-lord pull request #6
Opened 2022-11-04 15:41 UTC by Alucardik

2022-11-04 15:43 UTC, Alucardik commented on the_hammer_lord/controls/controls.py
>      _jumping: bool = False
Надо убрать отсюда

2022-11-04 15:44 UTC, Alucardik commented on the_hammer_lord/global_ctx.py
>  collidablesStorage = CollidablesStorage()
Тоже выпилить

2022-11-06 21:10 UTC, m-danya requested changes
здорово, продолжаем)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/controls/controls.py
> +class IControls(ABC):
I это потому что интерфейс?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/base.py
> +    # relative to the LEVEL coordinate system
Инт? А как так, а зачем? А почему?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/enemy.py
> +        # pygame.draw.rect(
если это всё равно придётся переписывать, то почему бы не стереть тогда это всё?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/level.py
> +        return (self._player.x - cur_screen_shift[0] > 0 and self._player.x + cur_screen_shift[0] < self._size[0],
black!!!

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/main.py
> -            # superkontik, will be removed (isn't it?)
это была шутка, его не надо было удалять............... верни........

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/collision_surface.py
> +            new_sprite.image = self._texture
эта строчка делает бесполезное действие, там дальше в 59 строке перезаписывается на другое

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/level.py
> +        self._floor.lock()
почему бы лок и анлок не делать внутри collidableSurface объекта? Это же его логика внутренняя и вроде можно изи запихнуть её внутрь add_breakpoints? пока не очень понимаю зачем вообще лочить

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/ui/health_bar.py
> +class HealthBar(StaticEntity):
почему статик, если оно движется вместе с плеером

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/base.py
> +class StaticEntity(ABC, BaseEntity, Sprite):
а что даёт наследование от Sprite?) 

а, нашёл, rect и image

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/base.py
> +class DynamicEntity(StaticEntity):
красиво, что от него наследуется плеер и переопределяет update

можно тоже абстрактным сделать, нет?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/enemy.py
> +        # pygame.draw.rect(
хотя по той же логике можно весь этот файл стереть. хм.

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/enemy.py
> +        # pygame.draw.rect(
ну и сотри реализацию `move` и `render` тогда, всё равно же придется  переписывать

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +        self._motion_vector[1] += GRAVITY_FORCE
Исаак Ньютон БЫЛ В ШОКЕ, когда узнал, КАК НА САМОМ ДЕЛЕ РАБОТАЕТ ГРАВИТАЦИЯ!!!!!!!

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +        shifted_pos = (pos[0] - self.rect.width // 2, pos[1] - self.rect.height // 2)
это же каждый ентити считать будет абсолютно одинаково по этой формуле, может тогда вынести в `BaseEntity`?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def move(self, ctrls_vector: Vector2D, land: bool = False):
~~а поч он везде называется motion_vector, а тут ctrls?~~
понял, немножко мутновато, но норм

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def move(self, ctrls_vector: Vector2D, land: bool = False):
`land` я бы переименовал во что-то вроде `is_on_land`

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def move(self, ctrls_vector: Vector2D, land: bool = False):
в идеале бы метод `move` сделать приватным и чтобы он вызвался из `update` из main.py с прокидыванием штук типа `is_on_land`, раз уж у нас наследование от `DymamicEntity` и все нпц будут так работать

можно тут обсудить в принципе или переделать чета

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    def move(self, ctrls_vector: Vector2D, land: bool = False):
может быть `jumping` заменить на `in_air`? так будет более очевидно, что падать тоже можно

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +        self.x += floor(self._motion_vector[0] * CAMERA_SPEED)
округлять приходится....

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/collision_surface.py
> +    _breakpoints: list[Point] = []
мб лучше _forming_ points, _образующие_ точки?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/collision_surface.py
> +            display.blit(rect_sprite.image, camera.calc_render_coords((rect_sprite.rect.x, rect_sprite.rect.y)))
почему тут считаются координаты через camera.calc_render_coords, а у плеера вручную как-то?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/level.py
> +        self._floor = CollisionSurface(SurfaceType.VERTICAL, self._size)
забавно, что пол — это вертикальная поверхность)) может поменять названия?

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/level.py
> +    _collidables: CollidablesStorage = CollidablesStorage()
забавно, что вот эта штука будет одна на все уровни. надо перенести инициализацию в `__init__`)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/level.py
> +        self._camera.move([0, 0])
ахахах забавный мув

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/main.py
> +    frame_cap = int(1e+9) // 240
может 240 это многовато?
интересно, что если поставить 1, то 
1) игра замедлится
2) cpu usage всё равно будет 100%...

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/main.py
> -        while unprocessed >= frame_cap:
ох лол кто это написал... (кто это скопировал со stackoverflow, я в принципе помню)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/main.py
> -        while unprocessed >= frame_cap:
а можно кстати внутри ифа сделать просто

`unprocessed %= frame_cap`

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/main.py
> -            # superkontik, will be removed (isn't it?)
(это шутка)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/types.py
> +Vector2D = list[float, float]
разве так можно? мне кжц только list[float] и всё

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/ui/health_bar.py
> +class HealthBar(StaticEntity):
я чета не понимаю видимо отличия между staticentity и dynamic

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/base.py
> +    def __init__(self, dimensions: Size2D, pos: Point = (0, 0)):
я бы назвал это size, потому что в коде я увидел и не понял че это (в healthbar-e, например)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/ui/health_bar.py
> +        # TODO: check if works
походу мы чекнули, раз (вроде) работает)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/utils/transform.py
> +            filled_surface.blit(tile, (x_shift * tile_sz[0], y_shift * tile_sz[1]))
ты смотрел, можно ли это оптимальнее сделать как-то, мб через группы какие-то? хотя мб и нельзя

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/utils/transform.py
> +            filled_surface.blit(tile, (x_shift * tile_sz[0], y_shift * tile_sz[1]))
типа попросить отрендерить группу тайлов сразу

может и не быть такого

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/utils/transform.py
> +    for y_shift in range(ceil(size[1] / tile_sz[1])):
ну это ни на что не влияет, но почему сначала по y?))

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/controls/controls.py
>      _motion_vector: Vector2D = [0, 0]
лучше внести инициализацию в `__init__`

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/entities/player.py
> +    _animations: dict[PlayerAction, list[Surface]] = {}
лучше внести инициализацию в `__init__` полей, а то они общими будут на объекты класса, вдруг у нас мультиплеер будет однажды...)

2022-11-06 21:10 UTC, m-danya commented on the_hammer_lord/level/collision_surface.py
> +    _breakpoints: list[Point] = []
тут точно обязательно нужно внести инициализацию в `__init__`!!

2022-11-07 11:46 UTC, dankondr requested changes
Читать мне, как непосвященному очень тяжело, явно не хватает дополнительных именованных абстракций. Хочется поменьше магии и побольше букв.

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/entities/enemy.py
> +        # )
Комментить код - плохая практика, это убивает смысл vcs, удали его и когда он будет нужен просто возьми из истории

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/entities/player.py
> +            for x in range(PLAYER_ANIMATIONS[action].frames_cnt):
Почему x, давай frame_idx

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/entities/player.py
>              # update image
Зачем этот коммент?)

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/entities/player.py
> +            # 2. extract each frame from it
Считается, что если надо писать где-то коммент, то стоит эту логику вынести в нормально именованную функцию.

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/level/collision_surface.py
> +    _breakpoints: list[Point] = []
Всё что объявлено в классе хранится в объекте класса (в питоне всё first class citizens), а что в __init__ в объектах инстанциации класса

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/level/collision_surface.py
> +                    cur_y = point[1]
Очень много магии, прошу выносить в функции с названиями

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/level/collision_surface.py
> +                    cur_y = point[1]
Для более сложных объектов имеет смысл сделать класс по паттерну Builder: https://refactoring.guru/design-patterns/builder

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/types.py
> +Vector2D = list[float, float]
Да,`list[float]` должно быть или же `tuple[float, float]`, но вообще я за то чтобы делать такие сущности через dataclass и работать с ними будет удобнее чем [0] [1]. типа:
```python
@dataclass
class Vector2D:
  x: float
  y: float

new_vec = Vector2D(10.0, 0.5)
new_vec.x += 1
```

2022-11-07 11:46 UTC, dankondr commented on the_hammer_lord/level/collision_surface.py
> +        self._form_rects()
В таких штуках всегда возможен race condition, лучше написать в комменте к классу, что он не thread-safe, а то потом можно соснуть

2022-11-07 16:32 UTC, m-danya commented on the_hammer_lord/level/collision_surface.py
> +        self._form_rects()
у нас пока что всё наверное не thread-safe, мы это не рассматриваем даже. Тут локи сделаны для эффективного формирования уровня, они не связаны с параллельным выполнением никак. Прикол в том, что в эту поверхность можно добавлять точки, и что когда добавление точно закончено (пока я не очень понимаю, когда это может быть отличным от добавления списка точек один раз, но Игорь говорит, что это на будущее, наверное, он видит, как это использоваться будет), надо вызвать `lock()`, чтобы отработала тяжеловесная штука по их обработке

2022-11-07 19:43 UTC, Alucardik commented on the_hammer_lord/controls/controls.py
> +class IControls(ABC):
Ага, в проде часто встречается такой нейминг, решил сюда тоже притащить

2022-11-07 19:43 UTC, Alucardik commented on the_hammer_lord/entities/base.py
> +    # relative to the LEVEL coordinate system
Обсуждали на звонке

2022-11-07 19:47 UTC, Alucardik commented on the_hammer_lord/level/collision_surface.py
> +            new_sprite.image = self._texture
Забыл удалить, когда переписывал

2022-11-07 19:47 UTC, Alucardik commented on the_hammer_lord/level/level.py
> +        self._floor.lock()
Тоже на звонке обсуждали

2022-11-07 19:47 UTC, Alucardik commented on the_hammer_lord/ui/health_bar.py
> +class HealthBar(StaticEntity):
Обсуждали на звонке

2022-11-07 19:48 UTC, Alucardik commented on the_hammer_lord/entities/base.py
> +class DynamicEntity(StaticEntity):
По идее он и так абстрактный, тк наследуется от абстрактного StaticEntity

2022-11-07 19:56 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +        shifted_pos = (pos[0] - self.rect.width // 2, pos[1] - self.rect.height // 2)
Мб, предлагаю тебе в следующем пр уже вынести если что) Тем более, что планируется выпилить BaseEntity, как обсудили на созвоне

2022-11-07 20:00 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +    def move(self, ctrls_vector: Vector2D, land: bool = False):
Мне кажется move вообще можно занести в DynamicEntity, тк они по задумке должны все же перемещаться... Опять же оставлю на твой пр)

Насчет is_on_land мне не нравится, тк длинновато и семантически неверно - тут land используется как "приземлиться". Типа надо приземляться или нет

В своем пр мб поудачнее подберешь нейминг после рефакторинга очередного)

2022-11-07 20:01 UTC, Alucardik commented on the_hammer_lord/entities/player.py
> +        self.x += floor(self._motion_vector[0] * CAMERA_SPEED)
Обсуждали на звонке

2022-11-07 20:03 UTC, Alucardik commented on the_hammer_lord/level/collision_surface.py
> +            display.blit(rect_sprite.image, camera.calc_render_coords((rect_sprite.rect.x, rect_sprite.rect.y)))
Сюда я все-таки передаю референс на камеру, тк приходится для каждого спрайта считать координаты

В игроке же это делается единожды, поэтому передаем уже готовые координаты для рендера

Ну и collisionSurface не оч вписывается пока в концепцию Dynamic / Static Enity, поэтому свой интерфейс

Мб сможешь подогнать под staticEntity

2022-11-07 20:03 UTC, Alucardik commented on the_hammer_lord/level/level.py
> +        self._floor = CollisionSurface(SurfaceType.VERTICAL, self._size)
Справедливо.

2022-11-07 20:05 UTC, Alucardik commented on the_hammer_lord/level/level.py
> +    _collidables: CollidablesStorage = CollidablesStorage()
Какая же питон глина...

2022-11-07 20:08 UTC, Alucardik commented on the_hammer_lord/main.py
> +    frame_cap = int(1e+9) // 240
Обсуждали на звонке, добавь `clock.tick(TARGET_FRAMERATE)` в своем pr

2022-11-07 20:16 UTC, Alucardik commented on the_hammer_lord/level/collision_surface.py
> +    _breakpoints: list[Point] = []
Справедливо

Насчет нейминга переделай в своем пр иф че)

2022-11-07 20:17 UTC, Alucardik commented on the_hammer_lord/main.py
> -        while unprocessed >= frame_cap:
В итоге выпилилось совсем)

2022-11-07 20:18 UTC, Alucardik commented on the_hammer_lord/types.py
> +Vector2D = list[float, float]
Это говно нужно переделать на `pygame.math.Vector2`, там уже есть все необходимые поля

Но не в этом пр)

2022-11-07 20:24 UTC, Alucardik commented on the_hammer_lord/utils/transform.py
> +            filled_surface.blit(tile, (x_shift * tile_sz[0], y_shift * tile_sz[1]))
Тут немного другая идея: функция заполняет тебе единожды новый surface тайлами, а дальше ты уже юзаешь заполненный Surface в рендеринге, пример в collisionSurface (двойных циклов в самом рендеринге офк нет)

Насчет именно более эффективного заполнения или нативного метода для подобного ничего не нашел (

Насчет групп: есть `Sprite.Group` класс, который позволяет выполнять действия на группой спрайтов, тот же коллективный update вызвать, но это по идее все еще простая обертка над Sprite, хотя я ее заюзал в collisionSurface

2022-11-07 20:26 UTC, Alucardik commented on the_hammer_lord/utils/transform.py
> +    for y_shift in range(ceil(size[1] / tile_sz[1])):
А наоборот он так сначала проходит внутренний цикл по x, и укладывает рядами текстуру

Мне просто укладками рядами кажется естественнее укладки столбцами) а так разницы и вправду нет

2022-11-07 20:29 UTC, Alucardik commented on the_hammer_lord/entities/player.py
>              # update image
Расширил пояснение

2022-11-07 20:36 UTC, Alucardik commented on the_hammer_lord/entities/base.py
> +    def __init__(self, dimensions: Size2D, pos: Point = (0, 0)):
Наверное, можно и size, но мне, наоборот, dimensions показательнее кажется... Вкусовщина) Можешь переписать

2022-11-08 09:32 UTC, m-danya commented on the_hammer_lord/utils/transform.py
> +            filled_surface.blit(tile, (x_shift * tile_sz[0], y_shift * tile_sz[1]))
ааа понял, прикольно, посмотрю ещё)

2022-11-08 09:35 UTC, m-danya approved these changes
LGTM, как говорится)

2022-11-08 09:36 UTC, dankondr commented
> LGTM, как говорится)

lets gamble, try merging?

2022-11-08 09:48 UTC, merged